name: Confirm Label
description: Create a status check with the API
inputs:
  github-token:
    description: Token provided by GitHub
    required: true
  pull-number:
    description: The number of the pull request triggering the action
    required: false
outputs:
  labels:
    description: A list of the labels
runs:
  using: node12
  main: index.js
